# TCL File Generated by Component Editor 11.0sp1
# Thu Nov 01 13:08:07 GMT 2012
# DO NOT MODIFY


# +-----------------------------------
# | 
# | pwm_component "pwm_component" v1.0
# | null 2012.11.01.13:08:07
# | SOPC
# | 
# | C:/svn_working_copy/EDM_Standard/ip/pwm_component/pwm_component.vhd
# | 
# |    ./pwm.vhd syn, sim
# |    ./pwm_component.vhd syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module pwm_component
# | 
set_module_property DESCRIPTION SOPC
set_module_property NAME pwm_component
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME pwm_component
set_module_property TOP_LEVEL_HDL_FILE pwm_component.vhd
set_module_property TOP_LEVEL_HDL_MODULE pwm_component
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME pwm_component
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file pwm.vhd {SYNTHESIS SIMULATION}
add_file pwm_component.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point s1
# | 
add_interface s1 avalon end
set_interface_property s1 addressAlignment DYNAMIC
set_interface_property s1 addressUnits WORDS
set_interface_property s1 associatedClock s1_clk
set_interface_property s1 associatedReset reset_sink
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 isMemoryDevice false
set_interface_property s1 isNonVolatileStorage false
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 printableDevice false
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitTime 1
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0

set_interface_property s1 ENABLED true

add_interface_port s1 s1_write write Input 1
add_interface_port s1 s1_address address Input 2
add_interface_port s1 s1_writedata writedata Input 32
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ENABLED true

add_interface_port conduit_end pwm_out_1 export Output 1
add_interface_port conduit_end pwm_out_2 export Output 1
add_interface_port conduit_end pwm_out_3 export Output 1
add_interface_port conduit_end pwm_out_4 export Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset_sink
# | 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock s1_clk
set_interface_property reset_sink synchronousEdges DEASSERT

set_interface_property reset_sink ENABLED true

add_interface_port reset_sink s1_reset reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point s1_clk
# | 
add_interface s1_clk clock end
set_interface_property s1_clk clockRate 0

set_interface_property s1_clk ENABLED true

add_interface_port s1_clk s1_clk clk Input 1
# | 
# +-----------------------------------
